# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.5.3
_src_path: https://github.com/epics-containers/ioc-template
description: Generic IOC for the motorStanda (https://github.com/MichaS-git/motorStanda)
    module
git_platform: github.com
github_org: tausystems
name: ioc-motorstanda
repo_uri: git@github.com:tausystems/ioc-motorstanda.git
rtems: false
