# yaml-language-server: $schema=/tmp/ibek.ioc.schema.json

ioc_name: "{{ _global.get_env('IOC_NAME') }}"
description: "Standa controller that controls the H-tilt and V-tilt of the pointing into the OAP"

entities:
  - type: epics.EpicsEnvSet
    name: EPICS_TZ
    value: GMT0BST

  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"

  - type: motor.motorUtil
    P: "LaserTransport:PreOAPPointing:H:"

  - type: motor.motorUtil
    P: "LaserTransport:PreOAPPointing:V:"

  - type: asyn.AsynSerial
    name: "serial_preoap_point_h"
    port: "/dev/ttyACM0"
    baud: 9600
    bits: 8
    parity: N
    stop: 1
    crtscts: N
    input_eos: "\r"
    output_eos: "\r"

  - type: asyn.AsynSerial
    name: "serial_preoap_point_v"
    port: "/dev/ttyACM1"
    baud: 9600
    bits: 8
    parity: N
    stop: 1
    crtscts: N
    input_eos: "\r"
    output_eos: "\r"

  - type: motorStanda.StandaCreateController
    controllerName: "standa_preoap_point_h"
    asynPort: "serial_preoap_point_h"
    numAxes: 1
    movingPollPeriod: 100
    idlePollPeriod: 500

  - type: motorStanda.StandaCreateController
    controllerName: "standa_preoap_point_v"
    asynPort: "serial_preoap_point_v"
    numAxes: 1
    movingPollPeriod: 100
    idlePollPeriod: 500

  - type: motorStanda.standaAxis
    controller: "standa_preoap_point_h"
    P: "LaserTransport:PreOAPPointing:"
    M: "H"
    ADDR: 0
    DESC: "Pre-OAP Point - Horizontal Tilt"
    EGU: "mm"
    VMAX: 15.0
    VELO: 5.0
    VBAS: 0.1
    ACCL: 0.1
    BDST: 0
    BVEL: 1.0
    BACC: 2.0
    MRES: 0.000025
    PREC: 5

  - type: motorStanda.standaAxis
    controller: "standa_preoap_point_v"
    P: "LaserTransport:PreOAPPointing:"
    M: "V"
    ADDR: 1
    DESC: "Pre-OAP Point - Vertical Tilt"
    EGU: "mm"
    VMAX: 15.0
    VELO: 5.0
    VBAS: 0.1
    ACCL: 0.1
    BDST: 0
    BVEL: 1.0
    BACC: 2.0
    MRES: 0.000025
    PREC: 5